name: build4front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  http: ^0.13.6
  intl: ^0.20.2        
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.7 
  flutter_secure_storage: ^9.0.0
  dio: ^5.7.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.1.1

  
dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
