name: build4front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  http: ^0.13.6
  intl: ^0.20.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.7
  flutter_secure_storage: ^9.0.0
  dio: ^5.7.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.1.1
  pdf: ^3.11.0
  printing: ^5.13.0
  flutter_stripe: ^11.0.0
  file_picker: ^8.1.2
  path_provider: ^2.1.5
  open_filex: ^4.5.0
  permission_handler: ^11.3.1
  share_plus: ^10.0.2
  flutter_file_dialog: ^3.0.2
  flutter_markdown: ^0.6.23
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.7.0
  foundation: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

#  Launcher Icon generator config
flutter_icons:
  android: true
  ios: true
  image_path: assets/branding/logo.png
  min_sdk_android: 21
  remove_alpha_ios: true


#  Native splash generator config
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/branding/logo.png
  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    image: assets/branding/logo.png


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/branding/
    - assets/templates/Template.xlsx

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
